/**
 * Distributes secrets from the repo-root .env (the local master copy) to where they run.
 *
 *   node scripts/env-sync.ts --railway   push each service's secrets to Railway (stdin, never argv)
 *   node scripts/env-sync.ts --local     write apps/<app>/.env for local development
 *
 * Only secrets travel through here. Non-secret config and cross-service wiring
 * (URLs, "caller key = callee key" references) are declared in .railway/railway.ts.
 * Admin credentials (BETTER_STACK_API_KEY, RESEND_ADMIN_API_KEY, SUPABASE_*) never leave
 * the root .env. See docs/CONFIGURATION.md.
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { readRootEnv, requireVar, SERVICES, servicePrefix, type Service } from './lib/root-env.ts';

const env = readRootEnv();

/** Un-prefixed root keys that belong to exactly one service. */
const SHARED_SECRETS: Record<Service, string[]> = {
  intake: ['DATABASE_URL'],
  'figure-mock': [],
  chase: [],
  email: ['RESEND_API_KEY'],
};

/** `<SERVICE>__NAME` keys that are metadata for scripts, not service config. */
const SCRIPT_ONLY = new Set(['PUBLIC_URL']);

function secretsFor(service: Service): Record<string, string> {
  const prefix = servicePrefix(service);
  const secrets: Record<string, string> = {};
  for (const [key, value] of Object.entries(env)) {
    if (!key.startsWith(prefix)) continue;
    const name = key.slice(prefix.length);
    if (!SCRIPT_ONLY.has(name)) secrets[name] = value;
  }
  for (const key of SHARED_SECRETS[service]) secrets[key] = requireVar(env, key);
  return secrets;
}

function pushToRailway() {
  for (const service of SERVICES) {
    for (const [key, value] of Object.entries(secretsFor(service))) {
      execFileSync(
        'railway',
        ['variable', 'set', key, '--stdin', '--service', service, '--skip-deploys'],
        { input: value, stdio: ['pipe', 'ignore', 'inherit'] },
      );
      console.log(`railway ${service}: ${key} set`);
    }
  }
}

function writeLocal() {
  const key = (name: string) => requireVar(env, name);
  const common = { HOST: '::', LOG_LEVEL: 'debug', LOG_PRETTY: 'true' };
  // Locally we don't ship logs to the production Better Stack sources.
  const withoutBetterStack = (secrets: Record<string, string>) =>
    Object.fromEntries(Object.entries(secrets).filter(([k]) => !k.startsWith('BETTERSTACK_')));

  const files: Record<string, Record<string, string>> = {
    intake: {
      ...common,
      PORT: '4000',
      ...withoutBetterStack(secretsFor('intake')),
      FIGURE_API_URL: 'http://localhost:4001',
      FIGURE_API_KEY: key('FIGURE_MOCK__INTERNAL_API_KEY'),
      CHASE_API_URL: 'http://localhost:4002',
      CHASE_API_KEY: key('CHASE__INTERNAL_API_KEY'),
      CORS_ORIGINS: 'http://localhost:3000',
      ALLOW_MOCK_OVERRIDE: 'true',
      WEB_APP_URL: 'http://localhost:3000',
    },
    'figure-mock': {
      ...common,
      PORT: '4001',
      ...withoutBetterStack(secretsFor('figure-mock')),
      MOCK_MODE: 'deterministic',
    },
    chase: {
      ...common,
      PORT: '4002',
      ...withoutBetterStack(secretsFor('chase')),
      EMAIL_SERVICE_URL: 'http://localhost:4003',
      EMAIL_SERVICE_API_KEY: key('EMAIL__INTERNAL_API_KEY'),
      CHASE_REPLY_ADDRESS: 'reply@linkerclaw.ai',
    },
    email: {
      ...common,
      PORT: '4003',
      ...withoutBetterStack(secretsFor('email')),
      // Log instead of sending; set to `resend` to deliver real mail from local.
      EMAIL_PROVIDER: 'console',
      EMAIL_FROM: key('EMAIL_FROM'),
    },
    web: { NEXT_PUBLIC_API_URL: 'http://localhost:4000' },
  };

  for (const [app, values] of Object.entries(files)) {
    const body = Object.entries(values)
      .map(([k, v]) => (/^[\w@.:/+=,%-]*$/.test(v) ? `${k}=${v}` : `${k}='${v}'`))
      .join('\n');
    writeFileSync(
      new URL(`../apps/${app}/.env`, import.meta.url),
      `# Generated by scripts/env-sync.ts --local from the repo-root .env. Do not edit.\n${body}\n`,
      { mode: 0o600 },
    );
    console.log(`apps/${app}/.env written (${Object.keys(values).length} vars)`);
  }
}

if (process.argv.includes('--railway')) pushToRailway();
else if (process.argv.includes('--local')) writeLocal();
else {
  console.error('usage: node scripts/env-sync.ts --railway | --local');
  process.exit(1);
}
